### ISSUE TITLE
Add a Git ignore file to your project and insert node module in it

### ISSUE THREAD

**Issue by mloic47** [Devseptomerveille/BOM2-Test#1]
Node modules should never be pushed to git as it is heavy and mostly useless for other pc always add your node modules to the git ignore file do research and resolve this issue

**Comment by Devseptomerveille** [comment]
ok i will do some research on it

**Comment by mloic47** [comment]
It's not complicated it is just to add a file named .gitignore and inside you add the exact of the node modules foler

**Comment by mloic47** [comment]
@Devseptomerveille mark this as done if it done same as all your other issues
