### ISSUE TITLE
Do the refactoring code on the branchemerveillestageMvc and branchHistoricPage

### ISSUE THREAD

**Issue by Devseptomerveille** [Devseptomerveille/BOM2-Test#14]
I have to arrange my different tests created in my page folder for a better presentation of the code.
Do the refactoring code on both branches and then make a pull request for each of them to the develop branch

**Comment by mloic47** [comment]
alright create a branch for this issue and do all that concerns this issue on that branch make sure you commit your work after each step you take to accomplish this

**Comment by Devseptomerveille** [comment]
Ok well received
